import fs from "fs";
import path from "path";

const GENERATED_DIR = path.resolve(__dirname, "generated");
const INDEX_FILE = path.resolve(GENERATED_DIR, "index.d.ts");

const files = fs.readdirSync(GENERATED_DIR).filter(file => file.endsWith(".ts") && !file.endsWith('index.d.ts'));

const lines = [
    "// Auto-generated by generate-index.ts",
    "// Do not edit manually.\n",
    ...files.map(file => {
      const name = path.basename(file, ".ts");
      return `export * from "./${name}";`;
    })
];

fs.writeFileSync(INDEX_FILE, lines.join("\n") + "\n");

console.log(`✅ Generated index.d.ts with ${files.length} exports`);