name: release

on:
  push:
    branches: [main]

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: packages/typescript/package-lock.json

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: none, mbstring

      - name: Git Identity
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: ./scripts/release.sh

      - name: Push commit + tags (Go + PHP)
        run: git push --follow-tags

      - name: Publish NPM package (TypeScript)
        run: cd packages/typescript && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}